version: '2'
services:
  jenkins:
    build: jenkins/.
    ports:
    - "8282:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - slave  
  slave:
    build: jenkins-slave/.
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
