version: '2'

services:
  jenkins:
    build: jenkins/.
    ports:
    - "8282:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins:/var/jenkins_home
    depends_on:
    - slave

  slave:
    build: jenkins-slave/.
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - slave:/home/jenkins
    depends_on:
    - registry

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry

volumes:
    jenkins:
    slave:
    registry:
